services:
  mongodb:
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=onepet
    networks:
      - onepet

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8085:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    depends_on:
      - mongodb
    networks:
      - onepet

  redis:
    image: redis:latest
    networks:
      - onepet

networks:
  onepet:
    driver: bridge